# Generated by Django 6.0.7 on 2026-09-12 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
                (
                    "google_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "auth_provider",
                    models.CharField(
                        choices=[("email", "Email"), ("google", "Google")],
                        default="email",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Suspended", "Suspended"),
                            ("Blocked", "Blocked"),
                            ("Deleted", "Deleted"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="User_Profile",
            fields=[
                ("profile_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="users/profile/"
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "environmental_impact",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_uploads", models.PositiveIntegerField(default=0)),
                ("total_sales", models.PositiveIntegerField(default=0)),
                ("total_purchases", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="users.users",
                    ),
                ),
            ],
            options={
                "db_table": "user_profile",
            },
        ),
    ]
