# Generated by Django 6.0.7 on 2026-09-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP_Verification',
            fields=[
                ('otp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('otp_hash', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('remaker_register', 'ReMaker Registration'), ('remaker_login', 'ReMaker Login'), ('user_forgot_password', 'User Forgot Password')], max_length=40)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'otp_verification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='User_Profile',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
