# Generated by Django 6.0.7 on 2026-09-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp_verification_delete_user_profile_delete_users'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='otp_verification',
            index=models.Index(fields=['email', 'purpose', 'created_at'], name='otp_email_purpose_created_idx'),
        ),
    ]
