# Generated by Django 6.0.7 on 2026-09-12 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReMakers',
            fields=[
                ('remaker_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('auth_provider', models.CharField(choices=[('email', 'Email'), ('google', 'Google')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Blocked', 'Blocked'), ('Deleted', 'Deleted')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'remakers',
            },
        ),
        migrations.CreateModel(
            name='ReMaker_Profile',
            fields=[
                ('remaker_profile_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='remakers/profile/')),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('experience', models.CharField(blank=True, max_length=100, null=True)),
                ('certification', models.TextField(blank=True, null=True)),
                ('environmental_impact', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_uploads', models.PositiveIntegerField(default=0)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('total_purchases', models.PositiveIntegerField(default=0)),
                ('remaker', models.OneToOneField(db_column='remaker_id', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='remakers.remakers')),
            ],
            options={
                'db_table': 'remaker_profile',
            },
        ),
    ]
